name: 'myapp'
services:
  webapp:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - postgres
    environment:
      MODE: ${MODE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${SECRET_ISSUER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PROFILE_SERVICE_URL: ${PROFILE_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      VNPAY_TMNCODE: ${VNPAY_TMNCODE}
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY}
      INTERNAL_BASE_URL: ${INTERNAL_BASE_URL}
    ports:
      - ${APP_PORT}

  postgres:
    image: 'postgres:17'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "25432:5432"
