apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
  labels:
    app: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service-container
          imagePullPolicy: Always
          image: "761018889743.dkr.ecr.ap-southeast-2.amazonaws.com/course-microservice:latest"
          ports:
            - containerPort: 8082
          env:
            - name: MODE
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: MODE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: SECRET_ISSUER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: DB_USER
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: DB_PORT
            - name: PROFILE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: course-service-secret
                  key: PROFILE_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: course-cluster-ip-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
